### ISSUE TITLE
setuptools_scm very old

### ISSUE THREAD

**Issue by MininuxDev** [Tblue/python-jproperties#15]
`setup.py` is telling setuptools that it needs a version of setuptools_scm not newer than 4.0.0 (`setuptools_scm ~= 3.3.`) However the latest version of setuptools_scm is 6.0.1, so 4.0.0 is quite old.
I tried running `tox` with `setuptools_scm >= 3.3`, and on py27 and py39 all the tests seem to pass.
edit: `python setup.py --version` seems to be correct too

**Comment by Tblue** [comment]
Fixed in e85ce0a410a9debb0126ee9bce4e7c0a7dfbf38f.
