### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by dmvieira** [Tblue/python-jproperties#2]
Do you have plans for python 3 support?

**Comment by Tblue** [comment]
Now that PR #1 is merged (thanks, @tboz203), Python 3 support is finally there! :-)

When I get home today, I will push release v2.0.0 to PyPI.

**Comment by rgbkrk** [comment]
Thank you @Tblue!

**Comment by Tblue** [comment]
Version 2.0.0 is now available on PyPI: https://pypi.org/project/jproperties/2.0.0/
