### ISSUE TITLE
Appending \ before :, how to remove that?

### ISSUE THREAD

**Issue by ukreddy-erwin** [Tblue/python-jproperties#3]
Sample code:
---------------
a.py
------
import os

from jproperties import Properties
p=Properties()

dbfile= "database.properties"
with open(dbfile,"r+b") as f:
	p.load(f,"utf-8")
    

p["URL"]=r"jdbc:oracle:thin:@//192.168.63.137:9002/xe"

with open(dbfile,"wb") as f:
	p.store(f,encoding="utf-8")

----------------------------------------
database.properties
----------------------
#Tue Feb 26 10:31:00 UTC 2019
DriverName=oracle.jdbc.OracleDriver
URL=sample_data
UserName=system
Password=oracle
PasswordEncrypted=false
DbType=ORACLESERVER
-------------------------------
[database.zip](https://github.com/Tblue/python-jproperties/files/2905000/database.zip)

Writing as jdbc\:oracle\:thin\:@//192.168.63.137\:9002/xe
instead of jdbc:oracle:thin:@//192.168.63.137:9002/xe

**Comment by Tblue** [comment]
For brevity, allow me to quote the property file that your script generates:

```properties
URL=jdbc\:oracle\:thin\:@//192.168.63.137\:9002/xe
```

You would like to remove the backslashes from the property value.

That is possible, but note that `\:` is a valid escape sequence according to the Java API: A conformant parser (such as Java's own parser, or jProperties) will replace `\:` by a single colon `:` when reading your property file, yielding the value that you originally specified in your script.

Unless you **know** that the property file will be read by a broken parser that does not decode the `\:` escape sequence, I would recommend to not interfere with how jProperties generates escape sequences: Doing that may produce broken property files that cannot be round-tripped correctly (i. e. parsing them produces different keys/values than specified when the property file was generated).

-----

Having said that, _if_ you really want to disable escape sequences in property values, that can be done by instantiating the `Properties` class like this:

```python
p = Properties(process_escapes_in_values=False)
# Your code here...
```

To quote the docstring for the `Properties` class:

> :param process_escapes_in_values: If False, do not process escape sequences in values when parsing and try hard not to produce any escape sequences when writing, i. e. output strings literally. However, some things like leading whitespace and newlines are always escaped (since there is not good way around this).
