### ISSUE TITLE
Parsing appends multiple ^@ and a date in the beginning of the file.

### ISSUE THREAD

**Issue by vinaymorkar** [Tblue/python-jproperties#6]
^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@#Wed Dec 18 11:14:54 UTC 2019

Need some mechanism to get rid of the above string/characters.

**Comment by Tblue** [comment]
Do you mean "writing" instead of parsing?

Please include a code example showing how you create the file. :)

**Comment by vinaymorkar** [comment]
Hi,
Thank you for your response. Here is my script:

from jproperties import Properties
import json
import os


#path to the json file where private properties are kept.
CONFIG_JSON_PATH = os.environ["CONFIG_FILE_PATH"]

#convert json into dict.
input_file = open (CONFIG_JSON_PATH)
projects = json.load(input_file)

#Iterate over projects to get the files and the keys of the properties from config.json that needs to be changed and update it using jproperties library.
for project in projects:
    for file in project['files']:
        for key in file['keys']:
            p = Properties()
            with open(os.environ["APP_HOME"]+'/'+project['projectName']+'/config/'+file['fileName'], "r+b") as f:
                p.load(f, "utf-8")
                p[key]=file['values'][key]
                f.truncate(0)
                strip_meta=False
                p.store(f, encoding="utf-8")

**Comment by vinaymorkar** [comment]
`from jproperties import Properties
import json
import os


#path to the json file where private properties are kept.
CONFIG_JSON_PATH = os.environ["CONFIG_FILE_PATH"]

#convert json into dict.
input_file = open (CONFIG_JSON_PATH)
projects = json.load(input_file)

#Iterate over projects to get the files and the keys of the properties from config.json that needs to be changed and update it using jproperties library.
for project in projects:
    for file in project['files']:
        for key in file['keys']:
            p = Properties()
            with open(os.environ["GROMOR_HOME"]+'/'+project['projectName']+'/config/'+file['fileName'], "r+b") as f:
                p.load(f, "utf-8")
                p[key]=file['values'][key]
                f.truncate(0)
                strip_meta=False
                p.store(f, encoding="utf-8")`

**Comment by Tblue** [comment]
Sorry for the late reply... And merry christmas!

Could you please also provide a sample property file? If possible, please upload it somewhere instead of pasting its contents so that any strange characters etc. are preserved.

I _suppose_ the `^@` characters are your editor's representation of the ASCII NUL character -- now we just need to find out how they get there.

You can suppress the timestamp by providing the `timestamp` keyword argument to the `store()` method, like so:

```python
 p.store(f, encoding="utf-8", timestamp=False)
```

**Comment by vinaymorkar** [comment]
Hey that's ok and merry Christmas to you too.

Here is the link of a sample property file.
https://drive.google.com/open?id=1NY645ks-oba4VSDiC0yITcWqFpdOryyj

I also have explored so many things but couldn't find a meaningful solution.
I have made a few changes in my script which helped me in fixing the issue. 

**f.seek(0)**
p[key]=file['values'][key]
f.truncate(0)
p.store(f,initial_comments=None,encoding='utf-8',strict=False,strip_meta=False,timestamp=False)

**Comment by Tblue** [comment]
```python
f.seek(0)
# ...
f.truncate(0)
```

Ah, I see. In retrospect, that makes sense: Calling just `f.truncate(0)` without calling `f.seek(0)` would truncate the file to 0 bytes, but leave the file position untouched. The next write would then write to that file position, and anything before that file position would be filled with zero bytes (cf. [lseek(2)](https://manpages.debian.org/buster/manpages-dev/lseek.2.en.html)).

I wouldn't consider this a bug in jProperties as it might be a valid use case to let jProperties write to a non-zero file offset. :-)
