### ISSUE TITLE
Importing ABC directly from collections was deprecated and will be removed in Python 3.10

### ISSUE THREAD

**Issue by tirkarthi** [Tblue/python-jproperties#7]
```
jproperties.py
40:from collections import MutableMapping, namedtuple
```

**Comment by ChristianMertes** [comment]
Sorry @dineshtrivedi, didn't see that you had already fixed this or else I wouldn't have opened https://github.com/Tblue/python-jproperties/pull/14
Unfortunately, it would seem @Tblue has abandoned this project given that your PR has remained open for over a year now :/

**Comment by Tblue** [comment]
It's true, I didn't care very well for this project during the last few years. Sorry about that, I'll have a look at this MR -- and the others -- in the next days.

**Comment by ChristianMertes** [comment]
Hey, no worries! I'm glad to hear the project isn't abandoned! :)

**Comment by NargiT** [comment]
any news? 3.9 is already released
